version: '3.1'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - - webflux_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
volumes:
  webflux_data:

