
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: 123456
logging:
  level:
    data:
      r2dbc: DEBUG
server:
  error:
    include-stacktrace: on_param



